# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CMGetFitRankLoss <- function(Z, t, lambda, phi, Parabola) {
    .Call(`_harper_CMGetFitRankLoss`, Z, t, lambda, phi, Parabola)
}

minSSEC <- function(Q, Z) {
    .Call(`_harper_minSSEC`, Q, Z)
}

